In [33]:
import pandas as pd

In [34]:
heart_failure = pd.read_csv('../Data/heart.csv')
heart_failure

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [35]:
heart_failure.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 86.2 KB

In [36]:
heart_failure.shape

(918, 12)

In [37]:
heart_failure.value_counts()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease
40   M    ATA            140        289          0          Normal      172    N               0.0      Up        0               1
49   F    NAP            160        180          0          Normal      156    N               1.0      Flat      1               1
37   M    ATA            130        283          0          ST          98     N               0.0      Up        0               1
48   F    ASY            138        214          0          Normal      108    Y               1.5      Flat      1               1
54   M    NAP            150        195          0          Normal      122    N               0.0      Up        0               1
                                                                                                                                 ..
45   M    TA             110        264          0          Normal      132    N               1.2      Flat      1               1
68   M    ASY            144        193          1          Normal      141    N               3.4      Flat      1               1
57   M    ASY            130        131          0          Normal      115    Y               1.2      Flat      1               1
     F    ATA            130        236          0          LVH         174    N               0.0      Flat      1               1
38   M    NAP            138        175          0          Normal      173    N               0.0      Up        0               1
Name: count, Length: 918, dtype: int64

In [38]:
heart_failure.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [39]:
high_chol = heart_failure.loc[heart_failure['Cholesterol'] > 240]
print(high_chol)

     Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal
2     37   M           ATA        130          283          0         ST
5     39   M           NAP        120          339          0     Normal
9     48   F           ATA        120          284          0     Normal
15    54   F           ATA        120          273          0     Normal
..   ...  ..           ...        ...          ...        ...        ...
896   47   M           NAP        130          253          0     Normal
900   58   M           ASY        114          318          0         ST
906   55   F           ATA        132          342          0     Normal
912   57   F           ASY        140          241          0     Normal
913   45   M            TA        110          264          0     Normal

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease
0      172              N      0.0       Up             0
2       98              N      0.0       Up             0
5      170              N      0.0       Up             0
9      120              N      0.0       Up             0
15     150              N      1.5     Flat             0
..     ...            ...      ...      ...           ...
896    179              N      0.0       Up             0
900    140              N      4.4     Down             1
906    166              N      1.2       Up             0
912    123              Y      0.2     Flat             1
913    132              N      1.2     Flat             1

[355 rows x 12 columns]

In [40]:
disease_info = heart_failure.loc[heart_failure['HeartDisease'] == 1, ['Age', 'Sex']]
print(disease_info)

     Age Sex
1     49   F
3     48   F
8     37   M
11    58   M
13    49   M
..   ...  ..
912   57   F
913   45   M
914   68   M
915   57   M
916   57   F

[508 rows x 2 columns]

In [41]:
heart_failure.loc[0:5, 'Age': 'Cholesterol']

   Age Sex ChestPainType  RestingBP  Cholesterol
0   40   M           ATA        140          289
1   49   F           NAP        160          180
2   37   M           ATA        130          283
3   48   F           ASY        138          214
4   54   M           NAP        150          195
5   39   M           NAP        120          339

In [42]:
subset = heart_failure.iloc[:, 0:3]
print(subset)

     Age Sex ChestPainType
0     40   M           ATA
1     49   F           NAP
2     37   M           ATA
3     48   F           ASY
4     54   M           NAP
..   ...  ..           ...
913   45   M            TA
914   68   M           ASY
915   57   M           ASY
916   57   F           ATA
917   38   M           NAP

[918 rows x 3 columns]

In [43]:
subset = heart_failure.iloc[10:20, 2:5]
print(subset)

   ChestPainType  RestingBP  Cholesterol
10           NAP        130          211
11           ATA        136          164
12           ATA        120          204
13           ASY        140          234
14           NAP        115          211
15           ATA        120          273
16           ASY        110          196
17           ATA        120          201
18           ASY        100          248
19           ATA        120          267

In [44]:
heart_failure['HeartDisease'].value_counts()

HeartDisease
1    508
0    410
Name: count, dtype: int64

In [46]:
sorted_heart_failure = heart_failure.sort_values(by=['Age', 'Sex'])
print(sorted_heart_failure.head())

     Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
208   28   M           ATA        130          132          0        LVH
170   29   M           ATA        120          243          0     Normal
219   29   M           ATA        140          263          0     Normal
829   29   M           ATA        130          204          0        LVH
215   30   F            TA        170          237          0         ST

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease
208    185              N      0.0       Up             0
170    160              N      0.0       Up             0
219    170              N      0.0       Up             0
829    202              N      0.0       Up             0
215    170              N      0.0       Up             0

In [48]:
heart_failure.rename({'FastingBS': 'Fasting_Blood_Sugar', 'RestingECG': 'RestingEKG'}, axis=1, inplace=True)
heart_failure.head(10)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,Fasting_Blood_Sugar,RestingEKG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0

In [50]:
print(heart_failure.isnull().sum().sum())

0

In [51]:
print(heart_failure.duplicated().sum())

0